### ISSUE TITLE
How to transform β and yaw?

### ISSUE THREAD

**Issue by GuancongLuo** [Derekabc/PathTrackingBicycle#1]
Hi, Derekabc

Thank you for your share.

When I read the 'bicylemodel.py', I find 'def update' without β in 'class LinearbicycleModel(object)'.

def update(self, throttle, delta):

        delta = np.clip(delta, -max_steer, max_steer)

        self.x += self.v * np.cos(self.yaw) * dt
        self.y += self.v * np.sin(self.yaw) * dt
        self.yaw += self.v / L * np.tan(delta) * dt
        self.yaw = normalize_angle(self.yaw)
        self.v += throttle * dt

Could you tell me how to transform β only for yaw?

![image](https://user-images.githubusercontent.com/41011340/84147003-3ab1d680-aa8f-11ea-98eb-cb5afcedc1ae.png)

**Comment by DongChen06** [comment]
hi GuancongLuo, you can check the model here.  [linear bicycle model](https://github.com/AtsushiSakai/PyAdvancedControl/blob/master/steer_vehicle_model/kinematic_bicycle_model.py)

Of course you can add β to the model as mentioned in [this tutorial.](https://www.coursera.org/lecture/intro-self-driving-cars/lesson-2-the-kinematic-bicycle-model-Bi8yE) . I used the case "Rear Axle Bicycle Model" mentioned in that tutorial.  I hope it helps.
